### ISSUE TITLE
Remove $typeName and $unknown

### ISSUE THREAD

**Issue by netanel-utila** [bufbuild/protobuf-es#1016] opened 2024-11-10 14:25 UTC
Hi,

Is there any way to exclude $typeName and $unknown from the types? we don't want to expose this to our clients:

<img width="538" alt="Screenshot 2024-11-10 at 16 25 29" src="https://github.com/user-attachments/assets/4cf4f2ed-bc20-4481-9c4d-6a73b4f77e91">

Thanks

**Comment by timostamm** [comment] 2024-11-11 15:58
You can remove properties (and do much more) with [mapped types](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html). 

Here is an example for a Connect client that does not make properties optional, and strips the `$typeName` and `$unknown` properties: https://github.com/connectrpc/examples-es/tree/main/custom-client

The `OmitTypeName` type from this example might just be what you need.

**Comment by netanel-utila** [comment] 2024-11-11 17:37
I understand that it's possible to implement this; however, same as the timestamp issue, I thought this could be something incorporated as a plugin or something. This way, it would automatically generate the desired outcome and we won't need to create wrappers, etc.

**Comment by timostamm** [comment] 2024-11-19 14:20
Do you mean a plugin _option_ to disable `$typeName` and `$unknown`?

ts-proto has many plugin options and basically no runtime library. Protobuf-ES has a different approach - it generates very little code, hosts most functionality in the runtime library, and aims for a single way to do things. The practical advantage is that we can test correctness, which is infeasible with a large number of plugin options that can affect each other. 

Depending on your use case, it might be worth to write a Protobuf plugin that emits types without `$typeName` 🤔 

Regardless of the concrete way to disable `$typeName`, we're aware that the property has disadvantages. Closing as a duplicate of #994, which tracks making it optional.

**Closed by timostamm** 2024-11-19 14:20 UTC
