### ISSUE TITLE
Why is the 'message' type field set as optional?

### ISSUE THREAD

**Issue by Eddy-Jeon** [bufbuild/protobuf-es#671] opened 2024-01-19 06:39 UTC
https://github.com/bufbuild/protobuf-es/blob/b816fbe849accab8d99da4608cea4a7cdd345eec/packages/protoplugin/src/ecmascript/gencommon.ts#L114
As seen in the above code, every field of the 'message' type is set as optional. 
I anticipated that the 'message' type field would follow the 'optional' keyword pattern like other types.

I have also reviewed the documentation [link to the documentation](https://github.com/bufbuild/protobuf-es/blob/main/docs/generated_code.md#message-fields), but I couldn't find the reason why the 'message' type field is set as optional.

Could you please provide more insight into the rationale behind this design choice or direct me to relevant documentation?

**Comment by emcfarlane** [comment] 2024-01-20 00:29
Closing as a duplicate of https://github.com/bufbuild/protobuf-es/issues/532 . Messages can be empty which is represented as an undefined optional in Typescript. See the runtime docs for more info: https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#default-field-values

**Closed by emcfarlane** 2024-01-20 00:29 UTC
